/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyect3;

import javax.swing.JOptionPane;

/**
 *
 * @author paula
 */
public class Init extends javax.swing.JFrame {

    private Object r;
    private Object c;
    private Board board= new Board();
     
    /**
     * Creates new form Direction
     */
    public Init() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButon = new javax.swing.JButton();
        JCBRows = new javax.swing.JComboBox<>();
        JCBCols = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JButon.setText("Enter");
        JButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButonActionPerformed(evt);
            }
        });

        JCBRows.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "5", "4", "3" }));
        JCBRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBRowsActionPerformed(evt);
            }
        });

        JCBCols.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "12", "15", "20" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(JButon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(JCBRows, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(JCBCols, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBRows, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBCols, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButonActionPerformed
        r = JCBRows.getSelectedItem();
        c = JCBCols.getSelectedItem();
        
        if(board.esTablero(r,c)){
        Pentomino proyect = new Pentomino(r,c);
        proyect.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "                      ERROR DE TAMAÑO\n"
                        + "porfavor selecciona un tamaño de los siguientes\n"
                        + "               6x10 || 5x12 || 4x15 || 3x20 ");
        }
    }//GEN-LAST:event_JButonActionPerformed

    private void JCBRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBRowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBRowsActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Init().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButon;
    private javax.swing.JComboBox<String> JCBCols;
    private javax.swing.JComboBox<String> JCBRows;
    // End of variables declaration//GEN-END:variables
}
